version: "3.3"

services:

  immutableweb-org:
    build: .
    expose:
      - "3031"
    environment:
      - VIRTUAL_HOST=immutableweb.org
      - LETSENCRYPT_HOST=immutableweb.org
      - LETSENCRYPT_EMAIL=mayhem@gmail.com

networks:
  default:
    name: nginx-proxy
    external: true
